name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Fmt
      run: go fmt $(go list ./... | grep -v /vendor/)
    - name: Vet
      run: go vet $(go list ./... | grep -v /vendor/)
    - name: Test
      run: go test -race $(go list ./... | grep -v /vendor/)

